[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "artistradio"
version = "0.1.0"
description = "ArtistRadio Engine"
requires-python = ">=3.13"
dependencies = []


[project.scripts]
artist-radio = "src.cli.main:main"


[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]


[tool.pytest.ini_options]
pythonpath = [
    "."
]